version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Run Tests
          command: npm test
          
      - run:
          name: Upload coverage to CodeClimate
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
            npm test
            ./cc-test-reporter after-build --exit-code $?

workflows:
  version: 2
  build:
    jobs:
      - build
